on:
  pull_request:
    branches:
      - master
      - releases/*
  push:
    branches:
      - master
      - releases/*

name: Packman Test
jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
#      env:
#        USERNAME: ${{ secrets.USERNAME }}
#        PASSWORD: ${{ secrets.PASSWORD }}
      run: go test -parallel 1 ./...